export const faqs = [
  ["What is the SIE exam?", "The Securities Industry Essentials (SIE) exam is FINRA's introductory exam for people entering the securities industry. It has 75 multiple-choice questions, a 105-minute time limit, and covers four content areas."],
  ["How many questions are on the SIE exam?", "FINRA lists 75 questions. The content outline allocates 12 to Capital Markets, 33 to Products and Risks, 23 to Trading and Accounts, and 7 to the Regulatory Framework."],
  ["What score do you need to pass the SIE?", "FINRA lists a passing score of 70. A practice score can help identify what to review, but it cannot predict an official exam result."],
  ["How should I use SIE practice questions?", "Answer mixed questions regularly, read the explanation after every miss, then return to the domain that is costing you the most points. Save full timed mocks for checking your exam pacing."],
  ["Does Bona Fide replace FINRA materials?", "No. Bona Fide is an independent study tool. Its questions are written to the current FINRA outline, but candidates should still use FINRA's official content outline and exam information."],
  ["Is Bona Fide available on iPad?", "Yes. Bona Fide is built for iPhone and iPad. Your study progress stays on your device and the app does not require an account."],
];

export const guides = [
  {
    slug: "sie-exam-study-plan",
    title: "SIE Exam Study Plan: Build One Around Your Test Date",
    description: "Turn the FINRA outline, your exam date, and your weak domains into a practical SIE study plan.",
    h1: "How to build an SIE exam study plan that fits your test date",
    intro: "Start with the official FINRA outline, then make your study time follow the exam's weighting. Products and Risks is 44% of the SIE, so it deserves more practice than a small section even if it feels less familiar. Add daily mixed questions early, and use full mocks later to test timing.",
    screenshot: "home.jpg",
    screenshotAlt: "Bona Fide home screen with exam countdown, daily practice and readiness score",
    featureImage: "sie-exam-study-plan-feature.jpg",
    featureAlt: "SIE exam candidate planning study time at a desk with a calendar and tablet",
    sections: [
      ["Map the four SIE domains before making a calendar", "The SIE has four domains: Capital Markets (16%), Products and Risks (44%), Trading and Customer Accounts (31%), and Regulatory Framework (9%). Use those proportions to decide where your hours go. A plan that gives every topic the same time will underprepare the two sections that make up three quarters of the test."],
      ["Set a daily question target you can repeat", "Pick a question set that fits into an ordinary weekday. The useful number is the one you can keep doing when work is busy. After each set, read the explanation for every error and tag the concept you need to revisit. Bona Fide adjusts daily practice around the date you enter and keeps the next set visible on the home screen."],
      ["Use mock exams to test decisions under time", "A 75-question mock with 105 minutes gives you about 84 seconds per question. Take a mock after you have covered the outline once, then review the results by domain instead of treating the total as the only result. A low section score tells you where tomorrow's practice should begin."],
    ],
  },
  {
    slug: "sie-practice-questions",
    title: "SIE Practice Questions: How to Learn From Every Miss",
    description: "A practical loop for using SIE practice questions, answer explanations and targeted review.",
    h1: "How to use SIE practice questions without memorizing the answer key",
    intro: "SIE practice questions work best when each wrong answer changes what you do next. Identify the tested rule, read why your choice fails, and then return to that topic in a later mixed set. Repeating a familiar question until you recognize it is much less useful than explaining the rule in a new scenario.",
    screenshot: "quiz.jpg",
    screenshotAlt: "Bona Fide multiple-choice SIE practice question about market manipulation",
    featureImage: "sie-practice-questions-feature.jpg",
    featureAlt: "Learner comparing abstract answer cards while studying for a securities exam",
    sections: [
      ["Read the whole fact pattern first", "Many SIE questions turn on a word such as primary, secondary, discretionary, or prohibited. Before scanning choices, ask what the question is actually testing. This makes distractors easier to eliminate and builds the habit needed when the wording changes on the real exam."],
      ["Treat an explanation as a short lesson", "When you miss, do not stop at the correct letter. Find the rule that makes it correct and the assumption that made your selection wrong. Bona Fide shows a rationale for the choice you selected, so the feedback addresses the exact confusion rather than a generic answer key."],
      ["Mix old and weak topics", "Topic drills are good for learning a new concept. Mixed sets are better for deciding which rule applies without a hint. Alternate both modes: drill a weak domain, then test it among unrelated questions a day or two later."],
    ],
  },
  {
    slug: "sie-practice-exam",
    title: "SIE Practice Exam: Use a 75-Question Mock Properly",
    description: "How to take and review a timed SIE practice exam using FINRA's published structure.",
    h1: "How to take an SIE practice exam under realistic conditions",
    intro: "For a useful SIE practice exam, use 75 questions and a 105-minute clock, then review the result by domain. The point is not to recreate every detail of the real test. It is to see whether you can make decisions at pace, find weak areas, and revise your plan before exam day.",
    screenshot: "mock.jpg",
    screenshotAlt: "Bona Fide timed 75-question SIE mock exam screen",
    featureImage: "sie-practice-exam-feature.jpg",
    featureAlt: "Timed exam desk with an analog timer, answer sheets and pencil",
    sections: [
      ["Make the first mock a clean baseline", "Block 105 minutes, put away notes, and answer every question yourself. Flag uncertain items rather than spending several minutes on one. A baseline only helps if it shows what you know unaided."],
      ["Compare your result with the blueprint", "The total score matters, but the domain breakdown is more actionable. Products and Risks has 33 of the 75 questions, while Regulatory Framework has 7. Fixing a recurring error in a heavily weighted domain can move your preparation more than polishing a tiny section."],
      ["Review after the timer ends", "Go through every wrong answer and every flag. Write down whether the miss came from a knowledge gap, a wording error, or rushed reading. Then do a short targeted set before your next mock. FINRA's own practice test is also a useful official reference point."],
    ],
  },
  {
    slug: "sie-exam-readiness-score",
    title: "SIE Exam Readiness Score: What It Can and Cannot Tell You",
    description: "Use a SIE readiness score as a review signal, not a promise about exam day.",
    h1: "What an SIE exam readiness score should tell you",
    intro: "A readiness score is useful when it points to a concrete next task: practice Products and Risks, revisit trading rules, or take a timed mock. It should not be treated as an official prediction. FINRA does not publish the SIE cut-score calculation, and practice results always depend on the questions you happened to see.",
    screenshot: "readiness.jpg",
    screenshotAlt: "Bona Fide readiness screen with overall score and domain performance bars",
    featureImage: "sie-exam-readiness-score-feature.jpg",
    featureAlt: "Candidate studying a wall of four abstract progress bars",
    sections: [
      ["Look below the headline number", "An overall percentage can hide a large weakness in a high-weighted area. Bona Fide shows the four domains separately and calls out the one losing the most potential points, so the number turns into a study decision."],
      ["Use repeated practice to spot a pattern", "One short set is noisy. A score becomes more useful after you have answered questions across the outline and returned to topics after review. Look for steady improvement and fewer repeated rule errors, rather than chasing one perfect session."],
      ["Keep the claim modest", "The SIE result is determined by your official test. A study app can organize practice and estimate your coverage, but it cannot guarantee a pass. Keep using the official outline as the final list of what may be tested."],
    ],
  },
  {
    slug: "sie-exam-outline",
    title: "SIE Exam Outline: The Four FINRA Content Areas",
    description: "A study-focused explanation of the official SIE exam outline and its question weighting.",
    h1: "SIE exam outline: how the four FINRA domains are weighted",
    intro: "The FINRA SIE content outline divides the exam into four domains. Understanding Products and Their Risks is the largest at 44%, followed by Trading, Customer Accounts and Prohibited Activities at 31%. Use that weighting to guide practice, while still covering all four areas before test day.",
    screenshot: "home.jpg",
    screenshotAlt: "Bona Fide home screen highlighting Products and Risks as the study focus",
    featureImage: "sie-exam-outline-feature.jpg",
    featureAlt: "Four differently sized stacks of study cards representing the SIE outline",
    sections: [
      ["Capital Markets: 16%", "This domain covers market structure, offerings, economic factors, and the roles of regulators and participants. It is smaller than Products and Risks, but it supplies core vocabulary used in later questions."],
      ["Products and Risks: 44%", "This is the largest part of the outline, with 33 questions in FINRA's published allocation. It includes equity and debt securities, options, packaged products, and their risks. Give it the largest share of your calendar and return to it after each mock."],
      ["Trading, accounts and regulation: 40% together", "Trading, Customer Accounts and Prohibited Activities accounts for 31%, and the Regulatory Framework accounts for 9%. Practice them as distinct domains, then mix them with products questions so you get used to identifying the rule from the facts."],
    ],
  },
  {
    slug: "products-and-risks-sie",
    title: "How to Study Products and Risks for the SIE Exam",
    description: "A focused approach to the SIE's largest domain: products, risk and 33 of 75 questions.",
    h1: "How to study Products and Risks for the SIE exam",
    intro: "Products and Risks is 44% of the SIE, so it is usually the best place to spend extra study time. Learn each product by comparing its features, investor fit, tax treatment, liquidity and risk. Then practice choosing between similar concepts in question form.",
    screenshot: "tutor.jpg",
    screenshotAlt: "Bona Fide explanation and tutor conversation after an incorrect SIE answer",
    featureImage: "products-and-risks-sie-feature.jpg",
    featureAlt: "Study still life with a coin, magnifying glass and blank financial paper",
    sections: [
      ["Study comparisons instead of isolated definitions", "A definition alone is rarely enough. Put securities side by side: common stock and preferred stock, open-end funds and closed-end funds, bonds and bond funds. Ask what changes when rates move, who carries risk, and how an investor can sell."],
      ["Turn recurring errors into a short list", "If you repeatedly confuse a rule or product feature, write one plain-language note and revisit it before your next set. Avoid collecting a huge notebook of copied definitions. A small list of your own errors is more useful because it reflects the mistakes you actually make."],
      ["Ask for the missing distinction", "After an error, a helpful question is often narrower than 'why is this wrong?'. Ask what fact separates the correct choice from the closest distractor. Bona Fide's tutor has the question and your selected choice in context, so you can follow the explanation with that exact distinction."],
    ],
  },
];
